name: Publish VS Code Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
      - name: Lint & Build
        run: |
          npm run lint || true
          npm run compile
      - name: Publish
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
          PUBLISHER: ${{ secrets.PUBLISHER }}
        run: |
          npx vsce publish --pat $VSCE_TOKEN
      - name: Package artifact
        if: always()
        run: |
          npx vsce package
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: vsix
            path: '*.vsix'